// ==========================================================================
// NIFITIVA AUTOMATED PRODUCTS DATABASE - GENERATED BY THE ADMIN DASHBOARD
// DO NOT EDIT THIS FILE MANUALLY. IT WILL BE OVERWRITTEN UPON SYNC.
// ==========================================================================

const PRODUCTS_DATABASE = [
    {
        "id":  "prod_1",
        "title":  "3D Sandscape In Motion Display",
        "description":  "Mesmerizing moving sand picture that creates a dynamic, relaxing frame of shifting golden sands. A gorgeous tabletop accent for office desks or living room shelves.",
        "category":  "useful finds",
        "videoUrl":  "https://assets.mixkit.co/videos/preview/mixkit-cozy-living-room-with-warm-lamp-lighting-42358-large.mp4",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/2YMopVyFdSAndZYoVkVq2Z.webp",
        "price":  999,
        "originalPrice":  1999,
        "affiliateUrl":  "https://amzn.to/4wg0bKQ",
        "rating":  4.8,
        "views":  2540,
        "clicks":  184,
        "tags":  [
                     "#sandscape",
                     "#deskdecor",
                     "#aestheticfinds"
                 ]
    },
    {
        "id":  "prod_2",
        "title":  "LED Vine Wall Light",
        "description":  "Cozy, warm cascading artificial ivy leaves integrated with soft glowing micro-LED lights. Perfect for adding a magical, biological ambiance to bedrooms and reading nooks.",
        "category":  "lighting",
        "videoUrl":  "https://assets.mixkit.co/videos/preview/mixkit-steam-rising-from-a-cup-of-hot-coffee-42323-large.mp4",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/q7WAk8TY5PnEZacpYBwwA9.jpg",
        "price":  499,
        "originalPrice":  1299,
        "affiliateUrl":  "https://amzn.to/4d57NXW",
        "rating":  4.7,
        "views":  1890,
        "clicks":  92,
        "tags":  [
                     "#ledvines",
                     "#cozydecor",
                     "#lightinggoals"
                 ]
    },
    {
        "id":  "prod_3",
        "title":  "Aesthetic Room Decor Items",
        "description":  "Handpicked selection of modern minimalist vases and abstract ceramic artifacts. Curated specifically to transform empty console tables into highly-styled gallery spaces.",
        "category":  "decor",
        "videoUrl":  "",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/q8Gg8MXp2n8jxeVuHPQtZf.jpg",
        "price":  1290,
        "originalPrice":  2499,
        "affiliateUrl":  "https://amzn.to/4dvaNOA",
        "rating":  4.6,
        "views":  3200,
        "clicks":  140,
        "tags":  [
                     "#vases",
                     "#ceramic",
                     "#aestheticroom"
                 ]
    },
    {
        "id":  "prod_4",
        "title":  "3D Cube Pixelated Box Illusion Wall Sticker",
        "description":  "Striking geometric optical illusion wall decal that plays with perspective and depth. Adds an instant, artistic modern tech edge to accent walls.",
        "category":  "decor",
        "videoUrl":  "",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/3KBBEMhLiP4ohReDtq7Aj6.jpg",
        "price":  349,
        "originalPrice":  899,
        "affiliateUrl":  "https://amzn.to/4daXyRV",
        "rating":  4.5,
        "views":  1210,
        "clicks":  45,
        "tags":  [
                     "#opticalillusion",
                     "#wallart",
                     "#roomsticker"
                 ]
    },
    {
        "id":  "prod_5",
        "title":  "Neon LED Strip Lights",
        "description":  "Flexible, ultra-bright neon string lights designed to outline custom setups, desk backings, or headboards. High-intensity diffusion yields solid, continuous light lines.",
        "category":  "lighting",
        "videoUrl":  "",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/Stg5aG6yA3f8437dsEhLAe.jpg",
        "price":  799,
        "originalPrice":  1499,
        "affiliateUrl":  "https://amzn.to/3QWv9HN",
        "rating":  4.7,
        "views":  4120,
        "clicks":  312,
        "tags":  [
                     "#neonled",
                     "#setupdecor",
                     "#gaminglighting"
                 ]
    },
    {
        "id":  "prod_6",
        "title":  "Wireless Motion Sensor Light for Home",
        "description":  "Magnetic, rechargeable smart LED bars that illuminate automatically upon sensing movement. Sleek design fits under cabinets, inside wardrobes, or along dark stairways.",
        "category":  "lighting",
        "videoUrl":  "",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/qJiRxfsp6aXoJzNaf5XCJg.jpg",
        "price":  699,
        "originalPrice":  1299,
        "affiliateUrl":  "https://amzn.to/4f7mj3S",
        "rating":  4.6,
        "views":  2840,
        "clicks":  182,
        "tags":  [
                     "#motionled",
                     "#closetdecor",
                     "#smarthomelight"
                 ]
    },
    {
        "id":  "prod_7",
        "title":  "Big Square Mirror Stickers for Wall",
        "description":  "Acrylic adhesive mirror panels to construct customized patterns on hallways or doors. Creates a spacious feeling, bounces light, and adds geometric symmetry.",
        "category":  "decor",
        "videoUrl":  "",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/TGDeFtwF4VqaED4zBLnBkR.jpg",
        "price":  499,
        "originalPrice":  999,
        "affiliateUrl":  "https://amzn.to/4dfYxAt",
        "rating":  4.5,
        "views":  1940,
        "clicks":  74,
        "tags":  [
                     "#mirrorstickers",
                     "#hallwaygoals",
                     "#geometry"
                 ]
    },
    {
        "id":  "prod_8",
        "title":  "Peel and Stick Wall Tile",
        "description":  "Waterproof, realistic self-adhesive premium tiles for a luxurious and quick kitchen backsplash or bathroom visual upgrade.",
        "category":  "decor",
        "videoUrl":  "",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/7Lw7TMiaz4CnybrPCV5heU.jpg",
        "price":  599,
        "originalPrice":  1499,
        "affiliateUrl":  "https://amzn.to/4wcfEeY",
        "rating":  4.6,
        "views":  1540,
        "clicks":  62,
        "tags":  [
                     "#peeltiles",
                     "#kitchenhacks",
                     "#roomstyling"
                 ]
    },
    {
        "id":  "prod_9",
        "title":  "Motivational Wall Art Decor (Set of 9 Posters)",
        "description":  "Inspirational typographic art prints to build a motivating, high-aesthetic gallery wall in your study space or office.",
        "category":  "decor",
        "videoUrl":  "",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/hbviuBtthQjxtaxWjZ74Bo.jpg",
        "price":  399,
        "originalPrice":  999,
        "affiliateUrl":  "https://amzn.to/4etv880",
        "rating":  4.8,
        "views":  2210,
        "clicks":  95,
        "tags":  [
                     "#motivation",
                     "#studyart",
                     "#officedecor"
                 ]
    },
    {
        "id":  "prod_10",
        "title":  "Modern Wooden Pinecone Pendant Ceiling Light",
        "description":  "Architectural Scandinavian-style layered wooden ceiling light that casts gorgeous warm geometric shadows.",
        "category":  "lighting",
        "videoUrl":  "",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/u9Laig32U3ozxfEZgmysRG.jpg",
        "price":  2499,
        "originalPrice":  4999,
        "affiliateUrl":  "https://amzn.to/4ddbpXY",
        "rating":  4.9,
        "views":  1780,
        "clicks":  115,
        "tags":  [
                     "#pineconelight",
                     "#woodceiling",
                     "#aestheticlighting"
                 ]
    },
    {
        "id":  "prod_11",
        "title":  "Wood Computer Desk with Shelf",
        "description":  "Sleek, minimalist dual-level workspace featuring robust walnut finish and matching upper storage shelves.",
        "category":  "furniture",
        "videoUrl":  "",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/itZeaVjusTXaevhmxZYGQF.jpg",
        "price":  3999,
        "originalPrice":  7999,
        "affiliateUrl":  "https://amzn.to/42oEPxo",
        "rating":  4.7,
        "views":  1540,
        "clicks":  80,
        "tags":  [
                     "#desksetup",
                     "#woodcomputer",
                     "#workspaceideas"
                 ]
    },
    {
        "id":  "prod_12",
        "title":  "Star Projector Night Light",
        "description":  "Advanced planetary nebula cloud projection light with matching Bluetooth speakers for a full cosmos experience.",
        "category":  "lighting",
        "videoUrl":  "",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/GnSNskza6DUeoYm9b9VZd6.jpg",
        "price":  1899,
        "originalPrice":  3999,
        "affiliateUrl":  "https://amzn.to/49IKnGP",
        "rating":  4.8,
        "views":  5410,
        "clicks":  420,
        "tags":  [
                     "#starprojector",
                     "#nebulanight",
                     "#cosmicroom"
                 ]
    },
    {
        "id":  "prod_13",
        "title":  "Wave Arched Mirror (Beige \u0026 Cream)",
        "description":  "A breathtaking statement dressing mirror with a luxurious, sculptural waved frame in soft, cozy aesthetic colors.",
        "category":  "furniture",
        "videoUrl":  "https://assets.mixkit.co/videos/preview/mixkit-hands-of-a-man-typing-on-a-typewriter-41618-large.mp4",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/4ySBjtPu9TYZWyc7jmXdr9.jpg",
        "price":  4999,
        "originalPrice":  9999,
        "affiliateUrl":  "https://amzn.to/49euxnb",
        "rating":  4.9,
        "views":  8450,
        "clicks":  912,
        "tags":  [
                     "#wavemirror",
                     "#aestheticmirror",
                     "#roomgoals"
                 ]
    },
    {
        "id":  "prod_14",
        "title":  "Irregular Makeup Mirror Tabletop Vanity Mirror",
        "description":  "A high-end, frameless asymmetric vanity mirror with a matching organic wooden stand for retro dresser layouts.",
        "category":  "furniture",
        "videoUrl":  "",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/S3ohHeSQUy8BsYmVMQdhqd.jpg",
        "price":  899,
        "originalPrice":  1999,
        "affiliateUrl":  "https://amzn.to/49EpSeH",
        "rating":  4.7,
        "views":  6200,
        "clicks":  412,
        "tags":  [
                     "#irregularmirror",
                     "#makeupdecor",
                     "#tablemirror"
                 ]
    },
    {
        "id":  "prod_15",
        "title":  "PAINTINGMANTRA Vintage Blue Birds Wall Art (Set of 7)",
        "description":  "An elegant set of 7 vintage-style framed Indian wall art prints featuring detailed blue bird and floral patterns.",
        "category":  "decor",
        "videoUrl":  "",
        "imageUrl":  "images/vintage_birds_art.png",
        "price":  1499,
        "originalPrice":  2999,
        "affiliateUrl":  "https://amzn.to/4wTe9mf",
        "rating":  4.8,
        "views":  3940,
        "clicks":  284,
        "tags":  [
                     "#paintingmantra",
                     "#bluebirds",
                     "#wallart"
                 ]
    },
    {
        "id":  "prod_16",
        "title":  "Aesthetic LED Sunset Projection Lamp",
        "description":  "Bring the warm, soothing glow of a golden hour sunset right inside your bedroom. Features high-transmittance crystal lens and dynamic halo adjustment to set the perfect aesthetic vibe for your cozy reels.",
        "category":  "lighting",
        "videoUrl":  "https://assets.mixkit.co/videos/preview/mixkit-starry-night-sky-over-hills-43285-large.mp4",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/TGDeFtwF4VqaED4zBLnBkR.jpg",
        "price":  499,
        "originalPrice":  1299,
        "affiliateUrl":  "https://www.amazon.in/dp/B08XM3RHRK?tag=mallika-21",
        "rating":  4.8,
        "views":  1520,
        "clicks":  92,
        "tags":  [
                     "#sunsetlamp",
                     "#aestheticfinds",
                     "#lightingdesign"
                 ]
    },
    {
        "id":  "prod_17",
        "title":  "Magnetic Levitating Moon Lamp",
        "description":  "An extraordinary levitating 3D-printed moon lamp that floats and rotates silently in mid-air above its elegant dark walnut base. The ultimate high-tech floating decor piece to wow your guests.",
        "category":  "lighting",
        "videoUrl":  "https://assets.mixkit.co/videos/preview/mixkit-hands-of-a-man-typing-on-a-typewriter-41618-large.mp4",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/q7WAk8TY5PnEZacpYBwwA9.jpg",
        "price":  2999,
        "originalPrice":  5999,
        "affiliateUrl":  "https://www.amazon.in/dp/B07L5H82H6?tag=mallika-21",
        "rating":  4.9,
        "views":  2130,
        "clicks":  145,
        "tags":  [
                     "#levitatingmoon",
                     "#smartlighting",
                     "#deskhack"
                 ]
    },
    {
        "id":  "prod_18",
        "title":  "Cozy Cascading Artificial Ivy LED Vines",
        "description":  "Premium micro-LED warm copper wire lights integrated with lush artificial English ivy leaves. Perfect for hanging along headboards, windows, or reading nooks to build a cozy biological oasis.",
        "category":  "lighting",
        "videoUrl":  "https://assets.mixkit.co/videos/preview/mixkit-cozy-living-room-with-warm-lamp-lighting-42358-large.mp4",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/q7WAk8TY5PnEZacpYBwwA9.jpg",
        "price":  399,
        "originalPrice":  999,
        "affiliateUrl":  "https://www.amazon.in/dp/B09D8SWT6C?tag=mallika-21",
        "rating":  4.7,
        "views":  3410,
        "clicks":  218,
        "tags":  [
                     "#ledvines",
                     "#cozyroom",
                     "#roomtransformation"
                 ]
    },
    {
        "id":  "prod_19",
        "title":  "Aesthetic Minimalist Ceramic Flower Vase Set",
        "description":  "Handcrafted unglazed matte white donut ceramic vase set. Features a modern Nordic donut design with an elegant hollow center, creating an instant contemporary art exhibition on any shelf.",
        "category":  "decor",
        "videoUrl":  "",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/q8Gg8MXp2n8jxeVuHPQtZf.jpg",
        "price":  1199,
        "originalPrice":  2499,
        "affiliateUrl":  "https://www.amazon.in/dp/B09V7NTR9B?tag=mallika-21",
        "rating":  4.8,
        "views":  1890,
        "clicks":  112,
        "tags":  [
                     "#ceramicvase",
                     "#nordicdecor",
                     "#shelfstyling"
                 ]
    },
    {
        "id":  "prod_20",
        "title":  "Vintage Gold Ornate Dressing Mirror",
        "description":  "A majestic French Baroque-inspired dressing tabletop mirror with detailed floral ornate scrollwork and elegant antique gold finish. Instantly adds luxurious regal depth to your vanity table setup.",
        "category":  "furniture",
        "videoUrl":  "https://assets.mixkit.co/videos/preview/mixkit-hands-of-a-man-typing-on-a-typewriter-41618-large.mp4",
        "imageUrl":  "https://media.bio.site/sites/590d4e5c-2c2f-401d-acca-7d3d15156ab4/4ySBjtPu9TYZWyc7jmXdr9.jpg",
        "price":  1999,
        "originalPrice":  3999,
        "affiliateUrl":  "https://www.amazon.in/dp/B09FKK5R2D?tag=mallika-21",
        "rating":  4.8,
        "views":  2750,
        "clicks":  189,
        "tags":  [
                     "#vintagegoldmirror",
                     "#vanitysetup",
                     "#cozydecor"
                 ]
    }
];