const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const axios = require('axios');
const cheerio = require('cheerio');
const { exec } = require('child_process');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.static(path.join(__dirname, 'public')));

// Serve root storefront files locally for testing
app.get('/store.html', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});
app.get('/products.js', (req, res) => {
  res.sendFile(path.join(__dirname, 'products.js'));
});
app.get('/script.js', (req, res) => {
  res.sendFile(path.join(__dirname, 'script.js'));
});
app.get('/styles.css', (req, res) => {
  res.sendFile(path.join(__dirname, 'styles.css'));
});

// Database File Paths
const DATA_DIR = path.join(__dirname, 'data');
const PRODUCTS_FILE = path.join(DATA_DIR, 'products.json');
const SCHEDULE_FILE = path.join(DATA_DIR, 'schedule.json');
const CONFIG_FILE = path.join(DATA_DIR, 'config.json');
const ROOT_PRODUCTS_JS = path.join(__dirname, 'products.js');

// Ensure database folder and files exist
if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR);
}

const defaultConfigs = {
  amazonTag: "mallika-21",
  pinterestClientId: "",
  pinterestClientSecret: "",
  pinterestAccessToken: "",
  pinterestBoardId: "",
  pinterestBoardName: "Smart Home & Viral Finds",
  postingIntervalHours: 2,
  pinsPerDay: 8,
  simulationMode: true
};

if (!fs.existsSync(CONFIG_FILE)) {
  fs.writeFileSync(CONFIG_FILE, JSON.stringify(defaultConfigs, null, 2));
}
if (!fs.existsSync(PRODUCTS_FILE)) {
  fs.writeFileSync(PRODUCTS_FILE, JSON.stringify([], null, 2));
}
if (!fs.existsSync(SCHEDULE_FILE)) {
  fs.writeFileSync(SCHEDULE_FILE, JSON.stringify([], null, 2));
}

// --- DATABASE HELPERS ---
function readJSON(file, fallback = []) {
  try {
    if (!fs.existsSync(file)) return fallback;
    const data = fs.readFileSync(file, 'utf8');
    return JSON.parse(data);
  } catch (error) {
    console.error(`Error reading file ${file}:`, error);
    return fallback;
  }
}

function writeJSON(file, data) {
  try {
    fs.writeFileSync(file, JSON.stringify(data, null, 2));
    return true;
  } catch (error) {
    console.error(`Error writing file ${file}:`, error);
    return false;
  }
}

// Regenerate the static products.js inside the root folder
function rebuildStaticStorefrontProducts() {
  try {
    const products = readJSON(PRODUCTS_FILE);
    const fileContent = `// ==========================================================================
// NIFITIVA AUTOMATED PRODUCTS DATABASE - GENERATED BY THE ADMIN DASHBOARD
// DO NOT EDIT THIS FILE MANUALLY. IT WILL BE OVERWRITTEN UPON SYNC.
// ==========================================================================

const PRODUCTS_DATABASE = ${JSON.stringify(products, null, 2)};
`;
    fs.writeFileSync(ROOT_PRODUCTS_JS, fileContent, 'utf8');
    console.log(`[SYNC] Regenerated root products.js with ${products.length} items successfully.`);
    return true;
  } catch (error) {
    console.error('[SYNC] Error rebuilding products.js:', error);
    return false;
  }
}

// Inject Affiliate parameters into URLs (specifically Amazon India)
function injectAffiliateTag(url, tag) {
  if (!url) return '';
  if (!tag) return url;
  
  try {
    // Check if it's an Amazon link
    if (url.includes('amazon.in') || url.includes('amazon.com') || url.includes('amzn.to')) {
      const parsedUrl = new URL(url);
      parsedUrl.searchParams.set('tag', tag);
      return parsedUrl.toString();
    }
  } catch (e) {
    // Return original url if parsing fails
  }
  return url;
}

// --- REST API ENDPOINTS ---

// 1. CONFIGURATION ROUTES
app.get('/api/config', (req, res) => {
  const config = readJSON(CONFIG_FILE, defaultConfigs);
  res.json(config);
});

app.post('/api/config', (req, res) => {
  const currentConfig = readJSON(CONFIG_FILE, defaultConfigs);
  const updated = { ...currentConfig, ...req.body };
  
  if (writeJSON(CONFIG_FILE, updated)) {
    res.json(updated);
  } else {
    res.status(500).json({ error: 'Failed to save configuration.' });
  }
});

// 2. PRODUCTS CRUD ROUTES
app.get('/api/products', (req, res) => {
  const products = readJSON(PRODUCTS_FILE);
  res.json(products);
});

app.post('/api/products', (req, res) => {
  const products = readJSON(PRODUCTS_FILE);
  const config = readJSON(CONFIG_FILE, defaultConfigs);
  const productData = req.body;

  if (!productData.title || !productData.price) {
    return res.status(400).json({ error: 'Title and Price are required.' });
  }

  // Inject affiliate tag into product link
  const affiliateUrl = injectAffiliateTag(productData.affiliateUrl || 'https://www.amazon.in', config.amazonTag);

  const newProduct = {
    id: 'prod_' + Date.now() + '_' + Math.random().toString(36).substr(2, 5),
    title: productData.title,
    description: productData.description || '',
    category: productData.category || 'Viral Finds',
    videoUrl: productData.videoUrl || '',
    imageUrl: productData.imageUrl || 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
    price: Number(productData.price),
    originalPrice: Number(productData.originalPrice || productData.price * 2),
    affiliateUrl: affiliateUrl,
    rating: Number(productData.rating || 4.5),
    views: 0,
    clicks: 0,
    tags: productData.tags || []
  };

  products.push(newProduct);
  if (writeJSON(PRODUCTS_FILE, products)) {
    rebuildStaticStorefrontProducts();
    res.status(201).json(newProduct);
  } else {
    res.status(500).json({ error: 'Failed to save product.' });
  }
});

app.put('/api/products/:id', (req, res) => {
  const products = readJSON(PRODUCTS_FILE);
  const config = readJSON(CONFIG_FILE, defaultConfigs);
  const { id } = req.params;
  const index = products.findIndex(p => p.id === id);

  if (index === -1) {
    return res.status(404).json({ error: 'Product not found.' });
  }

  const existing = products[index];
  const updateData = req.body;

  // Sync details
  if (updateData.title !== undefined) existing.title = updateData.title;
  if (updateData.description !== undefined) existing.description = updateData.description;
  if (updateData.category !== undefined) existing.category = updateData.category;
  if (updateData.videoUrl !== undefined) existing.videoUrl = updateData.videoUrl;
  if (updateData.imageUrl !== undefined) existing.imageUrl = updateData.imageUrl;
  if (updateData.price !== undefined) existing.price = Number(updateData.price);
  if (updateData.originalPrice !== undefined) existing.originalPrice = Number(updateData.originalPrice);
  if (updateData.rating !== undefined) existing.rating = Number(updateData.rating);
  if (updateData.tags !== undefined) existing.tags = updateData.tags;
  
  if (updateData.affiliateUrl !== undefined) {
    existing.affiliateUrl = injectAffiliateTag(updateData.affiliateUrl, config.amazonTag);
  }

  products[index] = existing;
  if (writeJSON(PRODUCTS_FILE, products)) {
    rebuildStaticStorefrontProducts();
    res.json(existing);
  } else {
    res.status(500).json({ error: 'Failed to update product.' });
  }
});

app.delete('/api/products/:id', (req, res) => {
  const products = readJSON(PRODUCTS_FILE);
  const { id } = req.params;
  const filtered = products.filter(p => p.id !== id);

  if (products.length === filtered.length) {
    return res.status(404).json({ error: 'Product not found.' });
  }

  if (writeJSON(PRODUCTS_FILE, filtered)) {
    rebuildStaticStorefrontProducts();
    res.json({ success: true, message: 'Product deleted.' });
  } else {
    res.status(500).json({ error: 'Failed to delete product.' });
  }
});

// Increments product click views (triggered upon redirect from storefront)
app.post('/api/products/:id/click', (req, res) => {
  const products = readJSON(PRODUCTS_FILE);
  const { id } = req.params;
  const index = products.findIndex(p => p.id === id);

  if (index !== -1) {
    products[index].clicks = (products[index].clicks || 0) + 1;
    writeJSON(PRODUCTS_FILE, products);
    rebuildStaticStorefrontProducts();
    res.json({ success: true, clicks: products[index].clicks });
  } else {
    res.status(404).json({ error: 'Product not found.' });
  }
});

// 3. PINTEREST SCRAPER & VIDEO DOWNLOADER
app.post('/api/pinterest/fetch', async (req, res) => {
  const { url } = req.body;
  if (!url) {
    return res.status(400).json({ error: 'Pinterest URL is required.' });
  }

  try {
    let targetUrl = url;
    // Resolve short.it redirect links
    if (url.includes('pin.it')) {
      const redirectRes = await axios.get(url, {
        maxRedirects: 5,
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        }
      });
      targetUrl = redirectRes.request.res.responseUrl || url;
    }

    const response = await axios.get(targetUrl, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'en-US,en;q=0.9'
      }
    });

    const html = response.data;
    const $ = cheerio.load(html);

    let title = $('meta[property="og:title"]').attr('content') || $('title').text() || 'Pinterest Pin';
    let description = $('meta[property="og:description"]').attr('content') || $('meta[name="description"]').attr('content') || '';
    let imageUrl = $('meta[property="og:image"]').attr('content') || '';
    let videoUrl = $('meta[property="og:video"]').attr('content') || $('meta[property="og:video:secure_url"]').attr('content') || '';

    title = title.replace(' | Pinterest', '').trim();

    // Check application/ld+json standard schema script block
    $('script[type="application/ld+json"]').each((i, elem) => {
      try {
        const json = JSON.parse($(elem).html());
        if (json) {
          const items = Array.isArray(json) ? json : [json];
          for (const item of items) {
            if (item['@type'] === 'VideoObject' || item.video) {
              const videoObj = item.video || item;
              if (videoObj.contentUrl) videoUrl = videoObj.contentUrl;
              if (videoObj.thumbnailUrl) imageUrl = videoObj.thumbnailUrl;
              if (item.name) title = item.name;
              if (item.description) description = item.description;
            } else if (item['@type'] === 'SocialMediaPosting' || item['@type'] === 'CreativeWork') {
              if (item.name) title = item.name;
              if (item.description) description = item.description;
              if (item.image) {
                imageUrl = Array.isArray(item.image) ? item.image[0] : (item.image.url || item.image);
              }
            }
          }
        }
      } catch (e) {}
    });

    // Cleanup Pinterest marketing descriptions
    description = description.replace(/Discover recipes, home ideas, style inspiration.*/i, '').trim();

    // Scan raw html using regex as last resort
    if (!videoUrl) {
      const mp4Regex = /"videoUrl"\s*:\s*"([^"]+)"/g;
      let match = mp4Regex.exec(html);
      if (match && match[1]) {
        videoUrl = match[1].replace(/\\u002F/g, '/');
      }
    }

    if (!videoUrl) {
      const pinimgVideoRegex = /https:\/\/v1\.pinimg\.com\/videos\/[^\s"']+\.mp4/g;
      let match = html.match(pinimgVideoRegex);
      if (match && match[0]) {
        videoUrl = match[0];
      }
    }

    // Extract tags
    const tags = [];
    const hashtagRegex = /#\w+/g;
    const matches = description.match(hashtagRegex);
    if (matches) {
      matches.forEach(tag => {
        if (!tags.includes(tag.toLowerCase())) {
          tags.push(tag.toLowerCase());
        }
      });
    }

    res.json({
      success: true,
      title: title.trim(),
      description: description.trim(),
      videoUrl: videoUrl || null,
      imageUrl: imageUrl || null,
      tags
    });

  } catch (error) {
    console.error('[SCRAPER] Pinterest fetch failed:', error.message);
    res.status(500).json({ error: 'Failed to scrape Pinterest pin. Make sure it is a valid public pin link.' });
  }
});

// 4. PINTEREST SCHEDULER ROUTES
app.get('/api/pinterest/schedule', (req, res) => {
  const schedule = readJSON(SCHEDULE_FILE);
  res.json(schedule);
});

app.post('/api/pinterest/schedule', (req, res) => {
  const schedule = readJSON(SCHEDULE_FILE);
  const { title, description, videoUrl, imageUrl, affiliateUrl, boardName, scheduleTime } = req.body;

  if (!title || (!videoUrl && !imageUrl) || !scheduleTime) {
    return res.status(400).json({ error: 'Title, media content, and Schedule Time are required.' });
  }

  const newScheduleItem = {
    id: 'pin_' + Date.now() + '_' + Math.random().toString(36).substr(2, 5),
    title: title.trim(),
    description: description || '',
    videoUrl: videoUrl || '',
    imageUrl: imageUrl || '',
    affiliateUrl: affiliateUrl || '',
    boardName: boardName || 'Viral Amazon Finds',
    scheduleTime: scheduleTime, // Format: YYYY-MM-DDTHH:MM
    status: 'Pending', // Pending, Posted, Failed
    pinUrl: '',
    postedTime: '',
    views: 0,
    clicks: 0
  };

  schedule.push(newScheduleItem);
  
  // Sort schedule queue by date chronological
  schedule.sort((a, b) => new Date(a.scheduleTime) - new Date(b.scheduleTime));

  if (writeJSON(SCHEDULE_FILE, schedule)) {
    res.status(201).json(newScheduleItem);
  } else {
    res.status(500).json({ error: 'Failed to schedule pin.' });
  }
});

app.delete('/api/pinterest/schedule/:id', (req, res) => {
  const schedule = readJSON(SCHEDULE_FILE);
  const { id } = req.params;
  const filtered = schedule.filter(s => s.id !== id);

  if (schedule.length === filtered.length) {
    return res.status(404).json({ error: 'Schedule pin not found.' });
  }

  if (writeJSON(SCHEDULE_FILE, filtered)) {
    res.json({ success: true, message: 'Scheduled Pin canceled.' });
  } else {
    res.status(500).json({ error: 'Failed to cancel scheduled pin.' });
  }
});

// 5. GITHUB PAGES ONE-CLICK COMMIT & PUSH
app.post('/api/github/push', (req, res) => {
  console.log('[GITHUB] Initiating 1-Click Sync to GitHub Pages...');
  const products = readJSON(PRODUCTS_FILE);

  // Execute Git Workflow
  exec('git add .', (err1, stdout1, stderr1) => {
    if (err1) {
      console.error('[GITHUB] git add failed:', stderr1);
      return res.status(500).json({ error: 'Git Add failed.', details: stderr1 });
    }

    const commitMsg = `Sync storefront: updated dynamic catalog to ${products.length} products.`;
    exec(`git commit -m "${commitMsg}"`, (err2, stdout2, stderr2) => {
      // Note: Git returns error if nothing to commit, check if it contains "nothing to commit" or similar
      if (err2 && !stdout2.includes('nothing to commit') && !stderr2.includes('nothing to commit')) {
        console.error('[GITHUB] git commit failed:', stderr2);
        return res.status(500).json({ error: 'Git Commit failed.', details: stderr2 });
      }

      exec('git push', (err3, stdout3, stderr3) => {
        if (err3) {
          console.error('[GITHUB] git push failed:', stderr3);
          return res.status(500).json({ error: 'Git Push failed. Make sure upstream credentials are set up.', details: stderr3 });
        }

        console.log('[GITHUB] Deployment successful!');
        res.json({
          success: true,
          message: 'Successfully deployed to GitHub Pages! Your site will reflect changes in a few moments.',
          consoleLog: [stdout1, stdout2, stdout3].join('\n')
        });
      });
    });
  });
});

// 6. ANALYTICS ROADMAP
app.get('/api/analytics', (req, res) => {
  const products = readJSON(PRODUCTS_FILE);
  const schedule = readJSON(SCHEDULE_FILE);

  let totalViews = 0;
  let totalClicks = 0;
  
  products.forEach(p => {
    totalViews += (p.views || 0);
    totalClicks += (p.clicks || 0);
  });

  schedule.forEach(s => {
    totalViews += (s.views || 0);
    totalClicks += (s.clicks || 0);
  });

  res.json({
    totalProducts: products.length,
    scheduledPins: schedule.filter(s => s.status === 'Pending').length,
    completedPins: schedule.filter(s => s.status === 'Posted').length,
    totalViews: totalViews,
    totalClicks: totalClicks,
    estEarnings: (totalClicks * 12.5) // Simulated earnings metric (e.g. average Rs.12.5 per click conversion)
  });
});

// --- BACKGROUND AUTOMATION SCHEDULE RUNNER ---
// Checks every 15 seconds for scheduled pins that need to be published
setInterval(async () => {
  const schedule = readJSON(SCHEDULE_FILE);
  const config = readJSON(CONFIG_FILE, defaultConfigs);
  const now = new Date();
  
  let modified = false;

  for (let i = 0; i < schedule.length; i++) {
    const item = schedule[i];
    if (item.status === 'Pending' && new Date(item.scheduleTime) <= now) {
      console.log(`[AUTOMATOR] Processing Scheduled Pin upload: "${item.title}"`);
      
      if (config.simulationMode) {
        // SIMULATED UPLOAD PROCESS
        item.status = 'Posted';
        item.postedTime = new Date().toISOString();
        item.pinUrl = `https://pinterest.com/pin/simulated_${Math.random().toString(36).substr(2, 9)}`;
        
        // Generate random organic metrics for simulated pins
        item.views = Math.floor(Math.random() * 250) + 50;
        item.clicks = Math.floor(item.views * (Math.random() * 0.15 + 0.02)); // 2-17% click-through rate

        // Auto-increment simulated views/clicks on the matching product too
        const products = readJSON(PRODUCTS_FILE);
        const matchIdx = products.findIndex(p => p.title.toLowerCase() === item.title.toLowerCase() || p.affiliateUrl === item.affiliateUrl);
        if (matchIdx !== -1) {
          products[matchIdx].views = (products[matchIdx].views || 0) + item.views;
          products[matchIdx].clicks = (products[matchIdx].clicks || 0) + item.clicks;
          writeJSON(PRODUCTS_FILE, products);
          rebuildStaticStorefrontProducts();
        }

        console.log(`[AUTOMATOR] [SIMULATION] Pin successfully posted to board "${item.boardName}". Direct Pin Link: ${item.pinUrl}`);
        modified = true;
      } else {
        // REAL PINTEREST API CREATION WORKFLOW
        try {
          if (!config.pinterestAccessToken || !config.pinterestBoardId) {
            console.error('[AUTOMATOR] [ERROR] Real Posting selected, but Access Token or Board ID is missing! Pin marked as Failed.');
            item.status = 'Failed';
            item.postedTime = new Date().toISOString();
            modified = true;
            continue;
          }

          // Create Pin Body for Pinterest API v5
          const pinBody = {
            title: item.title,
            description: item.description,
            link: item.affiliateUrl,
            board_id: config.pinterestBoardId,
            media_source: {
              source_type: 'image_url',
              url: item.videoUrl || item.imageUrl // Pinterest API v5 requires a media source url
            }
          };

          const pinResponse = await axios.post('https://api.pinterest.com/v5/pins', pinBody, {
            headers: {
              'Authorization': `Bearer ${config.pinterestAccessToken}`,
              'Content-Type': 'application/json'
            }
          });

          if (pinResponse.data && pinResponse.data.id) {
            item.status = 'Posted';
            item.postedTime = new Date().toISOString();
            item.pinUrl = `https://www.pinterest.com/pin/${pinResponse.data.id}/`;
            console.log(`[AUTOMATOR] [SUCCESS] Real Pinterest Pin Created! ID: ${pinResponse.data.id}`);
          } else {
            throw new Error('API returned unexpected response formatting.');
          }

        } catch (apiError) {
          console.error('[AUTOMATOR] [API ERROR] Failed to create Pin on Pinterest:', apiError.response ? apiError.response.data : apiError.message);
          item.status = 'Failed';
          item.postedTime = new Date().toISOString();
        }
        modified = true;
      }
    }
  }

  if (modified) {
    writeJSON(SCHEDULE_FILE, schedule);
  }
}, 15000);

// Start Server
app.listen(PORT, () => {
  console.log(`================================================================`);
  console.log(`🚀 NIFITIVA AFFILIATE AUTOMATION HUB ACTIVE`);
  console.log(`🔗 Local Administration Panel: http://localhost:${PORT}`);
  console.log(`🛍️ Customer Storefront Website (Local Dev): http://localhost:${PORT}/store.html`);
  console.log(`🌎 GitHub Pages Sync Directory: ${__dirname}`);
  console.log(`================================================================`);
});
