# ==========================================================================
# NIFITIVA AFFILIATE AUTOMATOR - BUILT-IN WINDOWS .NET DATABASE & WEB SERVER
# (Pure built-in PowerShell & .NET assemblies - NO Node.js required!)
# ==========================================================================

$port = 3000
$proxyPort = 8080

# Start background TCP proxy to rewrite Host headers (supports external tunnels/mobile)
$proxyScript = {
    param($lPort, $tPort)
    $proxyListener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Any, $lPort)
    $proxyListener.Start()
    while ($true) {
        try {
            $c = $proxyListener.AcceptTcpClient()
            $stream = $c.GetStream()
            $buffer = New-Object byte[] 65535
            $read = $stream.Read($buffer, 0, $buffer.Length)
            if ($read -gt 0) {
                $req = [System.Text.Encoding]::UTF8.GetString($buffer, 0, $read)
                $req = $req -replace "Host: .*`r`n", ("Host: localhost:" + $tPort + "`r`n")
                $target = New-Object System.Net.Sockets.TcpClient("127.0.0.1", $tPort)
                $tStream = $target.GetStream()
                $reqBytes = [System.Text.Encoding]::UTF8.GetBytes($req)
                $tStream.Write($reqBytes, 0, $reqBytes.Length)
                $tBuffer = New-Object byte[] 65535
                $tRead = $tStream.Read($tBuffer, 0, $tBuffer.Length)
                while ($tRead -gt 0) {
                    $stream.Write($tBuffer, 0, $tRead)
                    if ($tStream.DataAvailable) {
                        $tRead = $tStream.Read($tBuffer, 0, $tBuffer.Length)
                    } else {
                        break
                    }
                }
                $target.Close()
            }
            $c.Close()
        } catch {
            if ($null -ne $c) { $c.Close() }
        }
    }
}
try {
    $proxyPowerShell = [PowerShell]::Create().AddScript($proxyScript).AddArgument($proxyPort).AddArgument($port)
    $null = $proxyPowerShell.BeginInvoke()
} catch {}

$listener = New-Object System.Net.HttpListener
$listener.Prefixes.Add("http://localhost:$port/")

# Database File Configurations
$dataDir = Join-Path (Get-Location) "data"
$dbProducts = Join-Path $dataDir "products.json"
$dbSchedule = Join-Path $dataDir "schedule.json"
$dbConfig = Join-Path $dataDir "config.json"
$rootProductsJs = Join-Path (Get-Location) "products.js"

# Ensure data folder and default JSON databases exist
if (-not (Test-Path $dataDir)) {
    [System.IO.Directory]::CreateDirectory($dataDir)
}
if (-not (Test-Path $dbConfig)) {
    $defaultConfig = @{
        amazonTag = "mallika-21"
        pinterestClientId = ""
        pinterestClientSecret = ""
        pinterestAccessToken = ""
        pinterestBoardId = ""
        pinterestBoardName = "Smart Home & Viral Finds"
        postingIntervalHours = 2
        pinsPerDay = 8
        simulationMode = $true
    }
    $defaultConfig | ConvertTo-Json | Out-File $dbConfig -Encoding utf8
}
if (-not (Test-Path $dbProducts)) {
    "[]" | Out-File $dbProducts -Encoding utf8
}
if (-not (Test-Path $dbSchedule)) {
    "[]" | Out-File $dbSchedule -Encoding utf8
}

# --- DATABASE REST HELPERS ---
function Read-JSON($filePath) {
    try {
        if (-not (Test-Path $filePath)) { return @() }
        $content = [System.IO.File]::ReadAllText($filePath)
        if ([string]::IsNullOrWhiteSpace($content)) { return @() }
        $parsed = ConvertFrom-Json $content
        if ($null -eq $parsed) { return @() }
        return @($parsed)
    } catch {
        return @()
    }
}

function Write-JSON($filePath, $data) {
    try {
        $json = ConvertTo-Json $data -Depth 100
        [System.IO.File]::WriteAllText($filePath, $json)
        return $true
    } catch {
        return $false
    }
}

# Rebuild static products.js database for GitHub Pages storefront
function Rebuild-StaticStorefrontProducts {
    try {
        $products = Read-JSON $dbProducts
        $jsonStr = ConvertTo-Json $products -Depth 100
        $fileContent = @"
// ==========================================================================
// NIFITIVA AUTOMATED PRODUCTS DATABASE - GENERATED BY THE ADMIN DASHBOARD
// DO NOT EDIT THIS FILE MANUALLY. IT WILL BE OVERWRITTEN UPON SYNC.
// ==========================================================================

const PRODUCTS_DATABASE = $jsonStr;
"@
        [System.IO.File]::WriteAllText($rootProductsJs, $fileContent)
        return $true
    } catch {
        return $false
    }
}

# Inject Affiliate tag parameters
function Inject-AffiliateTag($url, $tag) {
    if ([string]::IsNullOrEmpty($url)) { return "" }
    if ([string]::IsNullOrEmpty($tag)) { return $url }
    
    if ($url.Contains("amazon.in") -or $url.Contains("amazon.com") -or $url.Contains("amzn.to")) {
        if ($url.Contains("?")) {
            if ($url.Contains("tag=")) {
                # Replace existing tag
                return $url -replace "tag=[^&]*", "tag=$tag"
            } else {
                return "$url&tag=$tag"
            }
        } else {
            return "$url?tag=$tag"
        }
    }
    return $url
}

# Set Console window specs
$host.UI.RawUI.WindowTitle = "Nifitiva Affiliate Automator Server"
Clear-Host
Write-Host "==================================================================" -ForegroundColor Cyan
Write-Host "🚀 NIFITIVA AFFILIATE AUTOMATION HUB RUNNING NATIVELY" -ForegroundColor Green
Write-Host "==================================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "[SUCCESS] Windows .NET Web Server online at: http://localhost:$port/" -ForegroundColor Green
Write-Host "[SUCCESS] View Local dev storefront at: http://localhost:$port/store.html" -ForegroundColor Green
Write-Host "[INFO] Local catalog save directory: $dbProducts" -ForegroundColor Gray
Write-Host "[INFO] Press [Ctrl + C] in this window to stop the server." -ForegroundColor Red
Write-Host ""
Write-Host "Listening for automation operations..." -ForegroundColor Gray

# Start Server Loop
try {
    $listener.Start()
    
    # Run Background Posting Scheduler Loop asynchronously using a script block inside timer or simple tick counter
    # In PowerShell, we can perform a quick check inside the loop below on each request, or every few cycles to process scheduled pins!
    $lastSchedulerCheck = [DateTime]::MinValue
    
    while ($listener.IsListening) {
        
        # --- BACKGROUND SCHEDULER ENGINE ---
        $now = [DateTime]::Now
        if (($now - $lastSchedulerCheck).TotalSeconds -ge 15) {
            $lastSchedulerCheck = $now
            
            $schedule = Read-JSON $dbSchedule
            $config = (Read-JSON $dbConfig)[0]
            $modified = $false
            
            foreach ($item in $schedule) {
                if ($item.status -eq "Pending" -and (Get-Date $item.scheduleTime) -le $now) {
                    Write-Host ("[AUTOMATOR] Processing Pin upload: " + $item.title) -ForegroundColor Yellow
                    
                    if ($config.simulationMode) {
                        # Virtual Simulation mode
                        $item.status = "Posted"
                        $item.postedTime = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ss")
                        $item.pinUrl = ("https://pinterest.com/pin/simulated_" + (New-Guid).Guid.Substring(0, 9))
                        $item.views = (Get-Random -Minimum 50 -Maximum 300)
                        $item.clicks = [Math]::Round($item.views * ((Get-Random -Minimum 2 -Maximum 15) / 100))
                        
                        # Add traffic/clicks to catalog item
                        $products = Read-JSON $dbProducts
                        foreach ($p in $products) {
                            if ($p.title -eq $item.title -or $p.affiliateUrl -eq $item.affiliateUrl) {
                                $p.views = [int]$p.views + $item.views
                                $p.clicks = [int]$p.clicks + $item.clicks
                            }
                        }
                        $null = Write-JSON $dbProducts $products
                        $null = Rebuild-StaticStorefrontProducts
                        
                        Write-Host ("[AUTOMATOR] [SIMULATION] Pin posted successfully to board: " + $item.boardName) -ForegroundColor Green
                        $modified = $true
                    } else {
                        # Real API creation
                        if ([string]::IsNullOrEmpty($config.pinterestAccessToken) -or [string]::IsNullOrEmpty($config.pinterestBoardId)) {
                            Write-Host "[AUTOMATOR] [ERROR] Pinterest details missing. Marked Failed." -ForegroundColor Red
                            $item.status = "Failed"
                            $item.postedTime = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ss")
                            $modified = $true
                        } else {
                            try {
                                $pinBody = @{
                                    title = $item.title
                                    description = $item.description
                                    link = $item.affiliateUrl
                                    board_id = $config.pinterestBoardId
                                    media_source = @{
                                        source_type = "image_url"
                                        url = if (-not [string]::IsNullOrEmpty($item.videoUrl)) { $item.videoUrl } else { $item.imageUrl }
                                    }
                                } | ConvertTo-Json
                                
                                $headers = @{
                                    "Authorization" = "Bearer " + $config.pinterestAccessToken
                                    "Content-Type" = "application/json"
                                }
                                
                                $res = Invoke-RestMethod -Uri "https://api.pinterest.com/v5/pins" -Method Post -Headers $headers -Body $pinBody
                                if ($null -ne $res.id) {
                                    $item.status = "Posted"
                                    $item.postedTime = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ss")
                                    $item.pinUrl = ("https://www.pinterest.com/pin/" + $res.id + "/")
                                    Write-Host "[AUTOMATOR] [SUCCESS] Real Pinterest Pin created!" -ForegroundColor Green
                                }
                            } catch {
                                Write-Host ("[AUTOMATOR] [API ERROR] Pinterest upload failed: " + $_.Exception.Message) -ForegroundColor Red
                                $item.status = "Failed"
                                $item.postedTime = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ss")
                            }
                            $modified = $true
                        }
                    }
                }
            }
            if ($modified) {
                $null = Write-JSON $dbSchedule $schedule
            }
        }
        
        # --- WEB REQUEST ROUTER ---
        try {
            $context = $listener.GetContext()
            $request = $context.Request
            $response = $context.Response
            
            $urlPath = $request.Url.LocalPath
            $method = $request.HttpMethod
            
            if ($urlPath -eq "/" -or $urlPath -eq "") { 
                $urlPath = "/index.html" 
            }
            
            # --- REST API HANDLER ---
            if ($urlPath.StartsWith("/api/")) {
                $response.ContentType = "application/json; charset=utf-8"
                $response.StatusCode = 200
                $responseBytes = @()
                
                # 1. CONFIGURATION APIs
                if ($urlPath -eq "/api/config") {
                    if ($method -eq "GET") {
                        $config = Read-JSON $dbConfig
                        $jsonStr = ConvertTo-Json $config[0] -Depth 100
                        $responseBytes = [System.Text.Encoding]::UTF8.GetBytes($jsonStr)
                    }
                    elseif ($method -eq "POST") {
                        $reader = New-Object System.IO.StreamReader($request.InputStream)
                        $body = $reader.ReadToEnd()
                        $reader.Close()
                        
                        $updatedConfig = ConvertFrom-Json $body
                        $current = (Read-JSON $dbConfig)[0]
                        
                        # Apply updates
                        foreach ($prop in $updatedConfig.psobject.properties) {
                            $current.($prop.Name) = $prop.Value
                        }
                        
                        if (Write-JSON $dbConfig $current) {
                            $jsonStr = ConvertTo-Json $current -Depth 100
                            $responseBytes = [System.Text.Encoding]::UTF8.GetBytes($jsonStr)
                        } else {
                            $response.StatusCode = 500
                        }
                    }
                }
                
                # 2. PRODUCTS APIs
                elseif ($urlPath -eq "/api/products") {
                    if ($method -eq "GET") {
                        $products = Read-JSON $dbProducts
                        $jsonStr = ConvertTo-Json $products -Depth 100
                        $responseBytes = [System.Text.Encoding]::UTF8.GetBytes($jsonStr)
                    }
                    elseif ($method -eq "POST") {
                        $reader = New-Object System.IO.StreamReader($request.InputStream)
                        $body = $reader.ReadToEnd()
                        $reader.Close()
                        
                        $prod = ConvertFrom-Json $body
                        $config = (Read-JSON $dbConfig)[0]
                        
                        # Auto inject affiliate link parameters
                        $affLink = Inject-AffiliateTag $prod.affiliateUrl $config.amazonTag
                        
                        $newProduct = @{
                            id = ("prod_" + (Get-Date -UFormat %s) + "_" + (New-Guid).Guid.Substring(0, 5))
                            title = $prod.title
                            description = if ($prod.description) { $prod.description } else { "" }
                            category = if ($prod.category) { $prod.category } else { "Viral Finds" }
                            videoUrl = if ($prod.videoUrl) { $prod.videoUrl } else { "" }
                            imageUrl = if ($prod.imageUrl) { $prod.imageUrl } else { "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600" }
                            price = [int]$prod.price
                            originalPrice = if ($prod.originalPrice) { [int]$prod.originalPrice } else { [int]$prod.price * 2 }
                            affiliateUrl = $affLink
                            rating = if ($prod.rating) { [double]$prod.rating } else { 4.5 }
                            views = 0
                            clicks = 0
                            tags = if ($prod.tags) { $prod.tags } else { @() }
                        }
                        
                        $products = @(Read-JSON $dbProducts)
                        $products += $newProduct
                        
                        if (Write-JSON $dbProducts $products) {
                            $null = Rebuild-StaticStorefrontProducts
                            $jsonStr = ConvertTo-Json $newProduct -Depth 100
                            $responseBytes = [System.Text.Encoding]::UTF8.GetBytes($jsonStr)
                            $response.StatusCode = 201
                        } else {
                            $response.StatusCode = 500
                        }
                    }
                }
                
                # INCREMENT CLICK COUNTER
                elseif ($urlPath.StartsWith("/api/products/") -and $urlPath.EndsWith("/click")) {
                    $prodId = $urlPath -replace "/api/products/", "" -replace "/click", ""
                    $products = Read-JSON $dbProducts
                    
                    $found = $false
                    foreach ($p in $products) {
                        if ($p.id -eq $prodId) {
                            $p.clicks = [int]$p.clicks + 1
                            $found = $true
                        }
                    }
                    if ($found) {
                        if (Write-JSON $dbProducts $products) {
                            $null = Rebuild-StaticStorefrontProducts
                            $responseBytes = [System.Text.Encoding]::UTF8.GetBytes('{"success": true}')
                        }
                    } else {
                        $response.StatusCode = 404
                    }
                }
                
                # 3. SCHEDULER APIs
                elseif ($urlPath -eq "/api/pinterest/schedule") {
                    if ($method -eq "GET") {
                        $schedule = Read-JSON $dbSchedule
                        $jsonStr = ConvertTo-Json $schedule -Depth 100
                        $responseBytes = [System.Text.Encoding]::UTF8.GetBytes($jsonStr)
                    }
                    elseif ($method -eq "POST") {
                        $reader = New-Object System.IO.StreamReader($request.InputStream)
                        $body = $reader.ReadToEnd()
                        $reader.Close()
                        
                        $item = ConvertFrom-Json $body
                        $newPin = @{
                            id = ("pin_" + (Get-Date -UFormat %s) + "_" + (New-Guid).Guid.Substring(0, 5))
                            title = $item.title
                            description = if ($item.description) { $item.description } else { "" }
                            videoUrl = if ($item.videoUrl) { $item.videoUrl } else { "" }
                            imageUrl = if ($item.imageUrl) { $item.imageUrl } else { "" }
                            affiliateUrl = if ($item.affiliateUrl) { $item.affiliateUrl } else { "" }
                            boardName = if ($item.boardName) { $item.boardName } else { "Viral Finds" }
                            scheduleTime = $item.scheduleTime
                            status = "Pending"
                            pinUrl = ""
                            postedTime = ""
                            views = 0
                            clicks = 0
                        }
                        
                        $schedule = @(Read-JSON $dbSchedule)
                        $schedule += $newPin
                        
                        # Sort queue chronologically
                        $schedule = $schedule | Sort-Object { Get-Date $_.scheduleTime }
                        
                        if (Write-JSON $dbSchedule $schedule) {
                            $jsonStr = ConvertTo-Json $newPin -Depth 100
                            $responseBytes = [System.Text.Encoding]::UTF8.GetBytes($jsonStr)
                            $response.StatusCode = 201
                        } else {
                            $response.StatusCode = 500
                        }
                    }
                }
                
                elseif ($urlPath.StartsWith("/api/pinterest/schedule/")) {
                    if ($method -eq "DELETE") {
                        $pinId = $urlPath.Substring(24) # characters after '/api/pinterest/schedule/'
                        $schedule = Read-JSON $dbSchedule
                        
                        $filtered = @()
                        $found = $false
                        foreach ($item in $schedule) {
                            if ($item.id -eq $pinId) {
                                $found = $true
                            } else {
                                $filtered += $item
                            }
                        }
                        
                        if ($found) {
                            if (Write-JSON $dbSchedule $filtered) {
                                $responseBytes = [System.Text.Encoding]::UTF8.GetBytes('{"success": true}')
                            } else {
                                $response.StatusCode = 500
                            }
                        } else {
                            $response.StatusCode = 404
                        }
                    }
                }
                
                # 4. GITHUB 1-CLICK DEPLOY API
                elseif ($urlPath -eq "/api/github/push" -and $method -eq "POST") {
                    $products = Read-JSON $dbProducts
                    Write-Host "[GITHUB] Initiating 1-Click Sync to GitHub Pages..." -ForegroundColor Cyan
                    
                    try {
                        # Execute Git commands locally in PowerShell
                        $out1 = git add . 2>&1
                        
                        $commitMsg = ("Sync storefront: updated dynamic catalog to " + $products.Count + " products.")
                        $out2 = git commit -m $commitMsg 2>&1
                        
                        $out3 = git push 2>&1
                        
                        $consoleText = "$out1`n$out2`n$out3"
                        $resBody = @{
                            success = $true
                            message = "Successfully deployed to GitHub Pages! Your site will reflect changes in a few moments."
                            consoleLog = $consoleText
                        } | ConvertTo-Json
                        
                        $responseBytes = [System.Text.Encoding]::UTF8.GetBytes($resBody)
                        Write-Host "[GITHUB] Sync completed successfully." -ForegroundColor Green
                    } catch {
                        $response.StatusCode = 500
                        $errDetails = $_.Exception.Message
                        $responseBytes = [System.Text.Encoding]::UTF8.GetBytes("`"error`": `"GitHub Sync failed`", `"details`": `"$errDetails`"")
                    }
                }
                
                # 5. ANALYTICS API
                elseif ($urlPath -eq "/api/analytics") {
                    $products = Read-JSON $dbProducts
                    $schedule = Read-JSON $dbSchedule
                    
                    $totalViews = 0
                    $totalClicks = 0
                    foreach ($p in $products) {
                        $totalViews += [int]$p.views
                        $totalClicks += [int]$p.clicks
                    }
                    foreach ($s in $schedule) {
                        $totalViews += [int]$s.views
                        $totalClicks += [int]$s.clicks
                    }
                    
                    $pendingCount = 0
                    $postedCount = 0
                    foreach ($s in $schedule) {
                        if ($s.status -eq "Pending") { $pendingCount++ }
                        if ($s.status -eq "Posted") { $postedCount++ }
                    }
                    
                    $analytics = @{
                        totalProducts = $products.Count
                        scheduledPins = $pendingCount
                        completedPins = $postedCount
                        totalViews = $totalViews
                        totalClicks = $totalClicks
                        estEarnings = ($totalClicks * 12.5) # Rs. 12.5 estimated per click
                    } | ConvertTo-Json
                    
                    $responseBytes = [System.Text.Encoding]::UTF8.GetBytes($analytics)
                }
                
                # Real Pinterest Scraper parser implemented natively in PowerShell
                elseif ($urlPath -eq "/api/pinterest/fetch" -and $method -eq "POST") {
                    $reader = New-Object System.IO.StreamReader($request.InputStream)
                    $body = $reader.ReadToEnd()
                    $reader.Close()
                    
                    try {
                        $reqData = ConvertFrom-Json $body
                        $pinUrl = $reqData.url
                        
                        # Resolve redirects (especially pin.it short links)
                        $targetUrl = $pinUrl
                        if ($pinUrl.Contains("pin.it")) {
                            $webClient = New-Object System.Net.WebClient
                            $webClient.Headers.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
                            try {
                                $headersOnly = Invoke-WebRequest -Uri $pinUrl -MaximumRedirection 0 -ErrorAction SilentlyContinue
                            } catch {
                                $targetUrl = $_.Exception.Response.Headers["Location"]
                            }
                            if ([string]::IsNullOrEmpty($targetUrl)) {
                                $targetUrl = $pinUrl
                            }
                        }
                        
                        # Fetch page HTML content
                        $webClient = New-Object System.Net.WebClient
                        $webClient.Headers.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
                        $webClient.Headers.Add("Accept-Language", "en-US,en;q=0.9")
                        $html = $webClient.DownloadString($targetUrl)
                        
                        # Regex match title, desc, image, video
                        $title = "Pinterest Pin"
                        if ($html -match '<meta property="og:title" content="([^"]+)"') {
                            $title = $Matches[1]
                        }
                        
                        $desc = ""
                        if ($html -match '<meta property="og:description" content="([^"]+)"') {
                            $desc = $Matches[1]
                        }
                        
                        $image = ""
                        if ($html -match '<meta property="og:image" content="([^"]+)"') {
                            $image = $Matches[1]
                        }
                        
                        $video = ""
                        if ($html -match '<meta property="og:video" content="([^"]+)"') {
                            $video = $Matches[1]
                        }
                        
                        if ([string]::IsNullOrEmpty($video) -and $html -match '"videoUrl"\s*:\s*"([^"]+)"') {
                            $video = $Matches[1].Replace("\u002F", "/")
                        }
                        
                        if ([string]::IsNullOrEmpty($video) -and $html -match 'https://v1\.pinimg\.com/videos/[^\s"''&>]+\.mp4') {
                            $video = $Matches[0]
                        }
                        
                        # Clean strings HTML entities
                        $title = [System.Web.HttpUtility]::HtmlDecode($title) -replace " \| Pinterest", ""
                        $desc = [System.Web.HttpUtility]::HtmlDecode($desc) -replace "Discover recipes, home ideas, style inspiration.*", ""
                        
                        $resObj = @{
                            success = $true
                            title = $title.Trim()
                            description = $desc.Trim()
                            videoUrl = $video
                            imageUrl = $image
                            tags = @()
                        } | ConvertTo-Json
                        
                        $responseBytes = [System.Text.Encoding]::UTF8.GetBytes($resObj)
                    } catch {
                        $response.StatusCode = 500
                        $errDetails = $_.Exception.Message
                        $responseBytes = [System.Text.Encoding]::UTF8.GetBytes("`"error`": `"Failed to scrape Pinterest pin`", `"details`": `"$errDetails`"")
                    }
                }
                
                # Write API Response stream
                $response.ContentLength64 = $responseBytes.Length
                $response.OutputStream.Write($responseBytes, 0, $responseBytes.Length)
            }
            
            # --- STATIC FILE HANDLER ---
            else {
                # Map local paths. If URL is /store.html or is storefront assets, map to root folder. 
                # Otherwise map to public/ folder!
                $filePath = ""
                if ($urlPath -eq "/store.html" -or $urlPath -eq "/products.js" -or $urlPath -eq "/script.js" -or $urlPath -eq "/styles.css") {
                    # Serves from ROOT folder
                    if ($urlPath -eq "/store.html") {
                        $filePath = Join-Path (Get-Location) "index.html"
                    } else {
                        $cleanedPath = $urlPath.Replace("/", "\").TrimStart("\")
                        $filePath = Join-Path (Get-Location) $cleanedPath
                    }
                } else {
                    # Serves from PUBLIC folder
                    $cleanedPath = $urlPath.Replace("/", "\").TrimStart("\")
                    $filePath = Join-Path (Get-Location) (Join-Path "public" $cleanedPath)
                }
                
                if (Test-Path $filePath -PathType Leaf) {
                    $bytes = [System.IO.File]::ReadAllBytes($filePath)
                    $ext = [System.IO.Path]::GetExtension($filePath).ToLower()
                    $contentType = "application/octet-stream"
                    
                    if ($ext -eq ".html") { $contentType = "text/html; charset=utf-8" }
                    elseif ($ext -eq ".css")  { $contentType = "text/css; charset=utf-8" }
                    elseif ($ext -eq ".js")   { $contentType = "application/javascript; charset=utf-8" }
                    elseif ($ext -eq ".png")  { $contentType = "image/png" }
                    elseif ($ext -eq ".jpg")  { $contentType = "image/jpeg" }
                    elseif ($ext -eq ".jpeg") { $contentType = "image/jpeg" }
                    elseif ($ext -eq ".svg")  { $contentType = "image/svg+xml" }
                    elseif ($ext -eq ".json") { $contentType = "application/json; charset=utf-8" }
                    
                    $response.ContentType = $contentType
                    $response.ContentLength64 = $bytes.Length
                    $response.OutputStream.Write($bytes, 0, $bytes.Length)
                } else {
                    $response.StatusCode = 404
                    $errBytes = [System.Text.Encoding]::UTF8.GetBytes("404 Page Not Found: $urlPath")
                    $response.OutputStream.Write($errBytes, 0, $errBytes.Length)
                }
            }
            $response.OutputStream.Close()
        } catch {
            # Catch individual connection interruptions quietly
        }
    }
} catch {
    Write-Host ("[ERROR] Failed to start server: " + $_.Exception.Message) -ForegroundColor Red
} finally {
    $listener.Stop()
    Write-Host "[INFO] Server stopped safely." -ForegroundColor Red
}
